version: '3.8'
services:
  backend:
    image: cursos-alura/vollmed-api # for using jar package - Dockerfile.1
    # build: . # for using maven - Dockerfile.2
    container_name: vollmed-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/vollmed_api
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      JWT_SECRET: docker-compose
      SPRING_CACHE_CAFFEINE_TOKEN-EXPIRATION: '20'

